# Variable
##### What is a Variable? 
A variable is a container that store values, it is also called a memory location.


In [2]:
Name = 'Olamide'

In [3]:
x=5 
y=7

In [4]:
x

5

In [5]:
print (x)

5


In [6]:
x+y
x/y

0.7142857142857143

## Rule of Variables
* ## Number 1: A variable must start with a letter (either upper case or lower case) or an underscore
  ##### A variable cannot start with a number.
  ##### A variable can only contain alphanumeric characters and underscores. (e.g, My_var 1)
  ##### Variable names are case sensitive.

In [8]:
name 

NameError: name 'name' is not defined

In [ ]:
1name 

In [ ]:
NAME == "Olamide"

In [ ]:
NAME = 'Olamide'

In [ ]:
NAME

In [ ]:
Name == NAME

In [ ]:
X = 21
Z = 25

In [ ]:
x = 21

In [ ]:
X == x

## Operators
* ##### Operetors are special symbols or keywords that are used to perform operations on variables and values.
* ##### They can manipulate data and variables to produce a result.
  Categories of Operators
* Arimethic operators: they perform basic mathematical operations.
* (+) : Addition
* Division operator : Floor(//) and Modulus(%) 
* Comparison operator: they compare two values and returns a boolean
* first one is 'equals to' (==)
* second one is not equals to (!=)
* third one is 'greater than' (>)
* fourth one is "less than" (<)
* greater than or equals (>=)
* less than or equals to (<=)
* Assignment operators (=) we use assignment operators to assign values to variable
* logical operators: First is "and" : it would return "true" is both conditions are true. Secondly, all would return "true" if at least one condition is true. Third, "not" it would return "false" if none is true.

In [ ]:
x = 7
y = 9

In [ ]:
x+y

In [ ]:
x-y

In [ ]:
x/y

In [ ]:
x*y

In [ ]:
a = 5
b = 2

In [ ]:
a/b

In [ ]:
a//b

In [ ]:
e = 4
f = 6

In [ ]:
e/f

In [ ]:
e//f

In [ ]:
g = 6
h = 4

In [ ]:
g/h

In [ ]:
g//h

In [ ]:
g != h

In [ ]:
City = "Lagos"
State = "Lagos"

In [ ]:
City == State

In [ ]:
import, for,

* ##### Python datatypes
* Numeric: Python numeric are numbers in python either intergers or decimals, numbers ranging from zero to infinity
* intergers: are whole numbers either positive or negative

In [ ]:
X = 2

In [ ]:
type (X)

In [ ]:
y = -2

In [ ]:
type (y)

What is a float: floats are numbers with decimal points either positive or negative

In [ ]:
z = 1.34

In [ ]:
type (z)

Characteristics of numeric datatypes
1. They are immutable :
2. it supports arimetic operations 

In [ ]:
x + z

In [ ]:
add (x+z)

Used case of python numeric datatypes, we used it for counting and indexing
while for float, we use it for precise calculations like averages and percentages

Python strings are sequence of characters (text) enclosed in quotes "" i.e strings are sequence data types

In [ ]:
Name = 'Olamide Awolaja'

In [ ]:
type (Name)

In [ ]:
Name [0]

In [ ]:
Name [7]

Characteristics of a string
1. It is immutable
2. They supports indexing and slicing (slicing is a process of extracting a character out)
3. 

In [ ]:
Name [-1]

In [ ]:
Name [1:4]

Why do I need to learn python case on strings i.e the use case of python strings
1. we used to store textual data. e.g names, address, gmail, etc

Python List:
1. A list is an ordered collection of items that can be changed. i.e mutable (flexible)
2. We can also say that "a list is an ordered collection of items seperated by commas and enclosed in square brackets" Cities = ["Ondo", "Ekiti", "Osun", "Oyo", "Ogun"]
3. you can mix integers with words or letters in a list e.g ["Ondo", "Ekiti", "Osun", "Oyo", "Ogun", 20, 27]


In [ ]:
Cities = ["Ondo", "Ekiti", "Osun", "Oyo", "Ogun", 20, 27]

In [ ]:
type (Cities)


In [ ]:
Cities [3]

In [ ]:
Cities [-1]

Used case scecenario of list
1. It is used for storing multiple values like rows of data

Tuple:
difference btw list and tuple : tuple uses curved brackets/parenthesis () while for list it is square brackets[] , and tuple is not mutable while list is mutable
Therefore a Tuple is an ordered collection of itmes that can be changed

In [2]:
my_tuple = (5, 6, 7, "hi", False)

In [4]:
my_tuple[1]

6

Dictionary : is a collection of key value pair
Characteristics: It is mutable like list and it allows fast lookup by keys.
Dictionary uses curly brackets

In [ ]:
Fellow = {"Name" : "Olamide", "Weight" : 65, "Age" : 36} 

In [ ]:
Fellow ['Name']

In [ ]:
Fellow ["Age"]

In [ ]:
Fellow [-1]

Conditional Statements
* ##### (If) statement: the If statement, tell us that if a condition is true. it would execute a block of statement. further, and if the condition is False, it won't execute the block.

In [ ]:
Age = 18
if Age >= 18:
    print ("Adult")
else: 
    print("Minor")

In [ ]:
Age = 19
if Age <= 18:
    print ("Adult")
else: 
    print("Minor")

In [ ]:
Age = 16
if Age >= 18:
    print ("Adult")
else: 
    print("Minor")

Used case scenario of Conditional Statement
1. Used to categorize outcome (yes/no, ages, sex:male/female
 

Functions
* ##### Functions are a block of statements that return a specific task. The idea is to put some commonly used or repeatedly done tasks together and make a function so that instead of writing the same code over again for different inputs we can do function calls to reuse code contained in it.

In [54]:
def check_even_odd(x):
    if x%2 == 0:
        return "even"
    else:
        return "odd"
(check_even_odd (20))

'even'

In [ ]:
check_even_odd (7)

In [ ]:
check_even_odd (2)

In [ ]:
check_even_odd (3)

In [ ]:
check_even_odd (10)

* ## LIBRARIES IN PYTHON 14 SEPTEMBER 2024
* ##### 1. PANDAS 2. MATPLOTLIB 3. SEABORN 4. NUMPY
* Numpy (numerical python) is a foundatonal package or library for numerical computation, particularly used for working with arrays.
* It provides support for large multidimensional arrays or matrices along with a collection of mathematical functions to operate these arrays.
* Before doing data analytics you need to import numpy as np.
* Numpy arrays are collection of elements of the same type whic are more efficient than python lists.
* 

In [2]:
arr = np.array([1,2,3,4,5])

NameError: name 'np' is not defined

In [5]:
import numpy as np


In [13]:
arr = np.array([1,2,3,4,5])

In [11]:
print array

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (4266615455.py, line 1)

In [12]:
print ('array')

array


In [14]:
print ('arr')

arr


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5])
    print ('arr')

IndentationError: unexpected indent (3271123170.py, line 3)

In [15]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [20]:
arr


array([1, 2, 3, 4, 5])

In [22]:
print (arr)

[1 2 3 4 5]


Arrays are used for storing large dataset, 

In [25]:
arr=np.array([4,5,6])
arr + 5


array([ 9, 10, 11])

In [27]:
arr*3

array([12, 15, 18])

In [29]:
arr/2

array([2. , 2.5, 3. ])

In [31]:
arr-2

array([2, 3, 4])

In [33]:
arr**2

array([16, 25, 36])

In [18]:
arr//2

array([0, 1, 1, 2, 2], dtype=int32)

In [37]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

In [41]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

* ## Basic Statistics in Numpy

In [44]:
arr=np.array([1,2,3,4,5])
np.sum(arr)

15

In [46]:
np.mean(arr)

3.0

In [48]:
np.min(arr)

1

In [50]:
np.max(arr)

5

In [52]:
np.std(arr)

1.4142135623730951

Sum, min, max and standard deviation are methods

Pandas ia powerful python library for data manipulation and analysis esp when working with structed data e.g csv, tabular data.
It is highly useful for data analysis becos it provides two (2) data structure: 1. Series(1D) and DataFrame (2D).
use this to import pandas "import pandas as pd"
Dataframe: 


In [24]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

# Display the DataFrame
df

Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [26]:
import pandas as pd

In [28]:
s=pd.Series([2,4,6,8,10])

In [63]:
s

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [65]:
df={'Name':['John', 'Ama', 'Peter'], 'Age':[28,24,35]}
pd.DataFrame(df)

Name  Age
0   John   28
1    Ama   24
2  Peter   35

In [67]:
df={'Name':['John', 'Ama', 'Peter'], 'Age':[28,24,35], 'Location': ['Ondo', 'Ogun', 'Lagos']}

In [69]:
pd.DataFrame(df)

Name  Age Location
0   John   28     Ondo
1    Ama   24     Ogun
2  Peter   35    Lagos

or method 